// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEgPeRHNmWZFrgNV4gQf8LVdnVHa0Ke4',
    appId: '1:250937130554:web:3c705c62ff5c7f94133f03',
    messagingSenderId: '250937130554',
    projectId: 'pdfapp-1e70e',
    authDomain: 'pdfapp-1e70e.firebaseapp.com',
    storageBucket: 'pdfapp-1e70e.firebasestorage.app',
    measurementId: 'G-R2CKC0VFFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSIiPpDE7GLVyUstehZ-RhNcJHKMCql8',
    appId: '1:250937130554:android:d53c651abb7dd0b2133f03',
    messagingSenderId: '250937130554',
    projectId: 'pdfapp-1e70e',
    storageBucket: 'pdfapp-1e70e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpL2pEuo5cFDu7Ek9-MF_QOQ-7T_WQdd8',
    appId: '1:250937130554:ios:c77deca29cead802133f03',
    messagingSenderId: '250937130554',
    projectId: 'pdfapp-1e70e',
    storageBucket: 'pdfapp-1e70e.firebasestorage.app',
    iosClientId: '250937130554-jdd9tjcpuf0qcabvt1s3h7rdi07kkn78.apps.googleusercontent.com',
    iosBundleId: 'com.legendarysoftware.imagetopdf',
  );

}